### PR TITLE
Again commit pregenerated bindings to the repository

### PR DESCRIPTION
**Pull request by stouset**

### CODE REVIEW

**Comment by stouset** [comment]
@ignatenkobrain Could I bother you to attempt to build this with a 32-bit target? I'm reapproaching committing pregenerated bindgen output from a different angle this time, and I want to make sure it doesn't break anything for your workflow.

**Comment by stouset** [comment]
Closes #65

**Comment by ignatenkobrain** [comment]
I guess this will fail on armv7hl, ppc64le and s390x, wouldn't it?

**Comment by stouset** [comment]
I’ll need to double-check in the morning that it should work on those arches, but I did provide a `generate_bindings` feature that will allow building on arches that we don’t have pre-generated bindings for.

**Comment by stouset** [comment]
@ignatenkobrain Yeah, while we don't have pre-generated bindings for those arches, compiling with the `generate_bindings` feature *should* work for any arch.

**Comment by klieth** [comment]
Seems sane to me. Does this make builds faster? More reproducible?

**Pull request merged**
